"""Type-only member declarations shared across the canvas mixins.

This module exists purely to give pyright/pylance the attributes, methods and
signals really provided at runtime by the composed ``PaintCanvas`` class (and its Qt
base). Each mixin lives in its own file, so a checker inspecting one mixin in
isolation cannot see members defined on its siblings or set in
``PaintCanvas.__init__``; without these stubs every such access was reported as
``reportAttributeAccessIssue``.

At runtime ``CanvasMembers`` is an empty ``object`` subclass, so mixing it in
is harmless. Under ``TYPE_CHECKING`` it inherits the real Qt base, so Qt
methods resolve too. A genuinely undefined name -- a typo or a removed
attribute -- still surfaces, because it never appears in this list.

Entries are being migrated from ``Any`` to their real types; every one that
moves off ``Any`` starts type-checking its own call sites, so prefer adding a
precise type here over widening one. ``Any`` remains the default for the many
method stubs, whose signatures live with the mixin that defines them.
"""
from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from PySide6.QtWidgets import QWidget
    from PySide6.QtCore import Signal
    from .document import Document
    from .models import Frame, Layer
    from .undo_entries import UndoEntry
    _MembersBase = QWidget
else:
    _MembersBase = object

class CanvasMembers(_MembersBase):
    if TYPE_CHECKING:
        cellChanged: Signal
        changed: Signal
        clipAnimationDropped: Signal
        colorSampled: Signal
        colorUsed: Signal
        imagesDropped: Signal
        onionInteractionChanged: Signal
        onionInteractionFinished: Signal
        projectDropped: Signal
        selectionChanged: Signal
        selectionCleared: Signal
        status_message: Signal
        timeRemapDropped: Signal
        viewChanged: Signal
        _active_mesh_cols: Any
        _active_mesh_rows: Any
        _active_tool_panel: Any
        _advance_stabilized_brush: Any
        _begin_onion_interaction_drag: Any
        _begin_opaque_brush_stroke: Any
        _binary_paint_overlay_rgba: Any
        _blend_overlay_into_active_layer: Any
        _bool_mask_image: Any
        _brush_blended_colors: Any
        _brush_cursor_inside: Any
        _brush_cursor_widget_pos: Any
        _brush_follow_settle: Any
        _brush_follow_timer: Any
        _brush_runtime_warmed: Any
        _brush_stabilizer_history: Any
        _brush_stabilizer_window: Any
        _brush_started_with_content: Any
        _build_playback_key_map: Any
        _build_tp_geometry_cache: Any
        _build_tp_label_image: Any
        _cell_structure_dirty: Any
        _clear_selection_state: Any
        _clear_timeline_layer_cell: Any
        _clear_tp_transform_masks: Any
        _cleared_selection_base: Any
        _color_filter_cache: Any
        _color_index_cache: Any
        _current_stroke_color: Any
        _curved_mesh_points: Any
        _display_layer_image: Any
        _document: Document
        _draw_onion_range: Any
        _draw_stabilized_brush_to: Any
        _draw_tapered_path: Any
        _emit_actual_paint_colors: Any
        _ensure_before_region: Any
        _ensure_frame_count: Any
        _eyedropper_cursor: Any
        _finish_opaque_brush_stroke: Any
        _finish_stabilized_brush: Any
        _hue_cluster_palette_from_samples: Any
        _invalidate_tp_preview_cache: Any
        _last_brush_pressure: Any
        _last_raw_canvas: Any
        _line_palette_labels: Any
        _line_preview_path: Any
        _local_color_variation: Any
        _make_white_transparent: Any
        _masked_selection_source: Any
        _median_cut_palette_from_samples: Any
        _mesh_catmull_scalar: Any
        _mesh_curve_point: Any
        _mesh_preview_image: Any
        _mesh_reference_grid: Any
        _merge_quality_transform: Any
        _natural_path_key: Any
        _normalized_angle: Any
        _onion_cache: Any
        _onion_frame_identity: Any
        _onion_frame_indices: Any
        _onion_interaction_axis: Any
        _onion_interaction_direction: Any
        _onion_interaction_dragging: Any
        _onion_interaction_mode: Any
        _onion_interaction_operation: Any
        _onion_interaction_start_next: Any
        _onion_interaction_start_next_rotation: Any
        _onion_interaction_start_next_scale: Any
        _onion_interaction_start_pan: Any
        _onion_interaction_start_previous: Any
        _onion_interaction_start_previous_rotation: Any
        _onion_interaction_start_previous_scale: Any
        _onion_interaction_start_tu_tb_scale: Any
        _onion_interaction_start_view_rotation: Any
        _onion_interaction_start_widget: Any
        _onion_widget_delta_to_canvas: Any
        _paint_rgb_palette: Any
        _pil_l_to_qimage: Any
        _pil_rgba_to_qimage: Any
        _place_imported_image: Any
        _playback_active: Any
        _playback_cache_dimensions: Any
        _playback_cache_limit: Any
        _playback_frame_cache: Any
        _playback_resolved_keys: Any
        _position_selection_clear_overlay: Any
        _prepare_draw_painter: Any
        _prepare_tp_transform_masks: Any
        _pressure_input_history: Any
        _priority_palette_colors_from_samples: Any
        _project_transform_source: Any
        _proxy_transform_preview_image: Any
        _qimage_gray_array: Any
        _qimage_rgba_array: Any
        _qimage_to_pil_rgba: Any
        _quad_homography: Any
        _read_image_file: Any
        _regular_grid_points: Any
        _regular_mesh_reference_points: Any
        _render_deferred_transform_line_preview: Any
        _reset_brush_stabilizer: Any
        _reset_selection_transform: Any
        _rgb_hsv_features: Any
        _rgba_array_to_qimage: Any
        _rotated_vector: Any
        _scanline_connected_region: Any
        _selection_blink_timer: Any
        _selection_fade_opacity: Any
        _selection_fade_started: Any
        _selection_source_from_image: Any
        _sequence_archive: Any
        _sequence_source_bank: Any
        _sequence_source_bank_layer_index: Any
        _sequence_source_bank_layer_name: Any
        _shape_path: Any
        _shape_rect: Any
        _shift_timeline_layer_left: Any
        _shift_timeline_layer_right: Any
        _silhouette_cache: Any
        _smooth_brush_pressure: Any
        _snap_overlay_to_exact_rgbs: Any
        _stabilized_brush_point: Any
        _stabilized_canvas: Any
        _start_brush_follow_timer: Any
        _stop_brush_follow_timer: Any
        _stroke_before_region: Any
        _stroke_before_tiles: Any
        _stroke_dirty_rect: Any
        _stroke_prev_has_content: Any
        _stroke_undo_frame: Any
        _stroke_undo_layer: Any
        _surface_guided_palette_labels: Any
        _tinted_onion_image: Any
        _tp_geometry_cache_bbox: Any
        _tp_geometry_cache_fill_overlay: Any
        _tp_geometry_cache_is_current: Any
        _tp_geometry_cache_key: Any
        _tp_geometry_cache_line_soft: Any
        _tp_geometry_key: Any
        _tp_inverse_mapper: Any
        _tp_label_colors: Any
        _tp_label_image: Any
        _tp_mask_key: Any
        _tp_mask_preview_image: Any
        _tp_mask_source_key: Any
        _tp_prepare_palette_image: Any
        _tp_preview_cache_image: Any
        _tp_preview_cache_key: Any
        _tp_preview_progress_busy: Any
        _tp_preview_progress_scheduled: Any
        _tp_proxy_rendering: Any
        _tp_proxy_source_image: Any
        _tp_proxy_source_key: Any
        _tp_transform_bbox: Any
        _tp_transparent_to_white: Any
        _tp_uses_proxy: Any
        _tp_white_to_transparent: Any
        _transform_is_reducing: Any
        _transform_line_adjusting: Any
        _transform_line_preview_timer: Any
        _trim_unused_trailing_frames: Any
        _update_onion_interaction_drag: Any
        _update_selection_clear_overlay: Any
        _update_selection_fade: Any
        _update_stroke_region: Any
        active_layer: Any
        active_layer_index: int
        add_frame: Any
        add_layer: Any
        apply_color_reduction_palette: Any
        apply_mesh_release: Any
        apply_selection_clip: Any
        apply_sequence_only_entries: Any
        apply_tone_curve: Any
        apply_undo_entry: Any
        auto_select_region: Any
        auto_select_used_area: Any
        background_mask_rgb: Any
        begin_onion_canvas_position_interaction: Any
        begin_onion_shift_interaction: Any
        begin_onion_transform_interaction: Any
        begin_selection_transform: Any
        begin_transform_drag: Any
        begin_transform_line_adjustment: Any
        binarize_alpha_for_pixel_art: Any
        brush_stabilizer_strength: Any
        fill_opacity: Any
        build_color_reduction_palette: Any
        cancel_mesh: Any
        cancel_onion_interaction: Any
        cancel_selection_transform: Any
        canvas_rect: Any
        canvas_to_widget: Any
        checker_dark: Any
        checker_light: Any
        clamped_index: Any
        clear_selection: Any
        clear_selection_preserving_used_colors: Any
        coalesce_numbered_images: Any
        color: Any
        color_mode: Any
        commit_line_tool: Any
        commit_mesh: Any
        commit_selection_transform: Any
        commit_shape_tool: Any
        composite: Any
        copy_selection: Any
        create_blank_key: Any
        current_exposure: Any
        current_frame: int
        current_state_for: Any
        cut_selection: Any
        delete_frame: Any
        delete_layer: Any
        delete_sequence_entry: Any
        detect_opaque_border_background: Any
        dilate: Any
        displacement_at: Any
        document_snapshot: Any
        draw_frame_direct: Any
        draw_line: Any
        drawing: Any
        effective_tool: Any
        end_transform_drag: Any
        ensure_editable_key: Any
        erode: Any
        estimate_mixed_boundary_pixels: Any
        fill_lasso_polygon: Any
        filtered_layer_image: Any
        _color_index_for_image: Any
        finish_transform_line_adjustment: Any
        flip_active_layer: Any
        flip_horizontal: bool
        flood_fill: Any
        frames: list[Frame]
        image_alpha_statistics: Any
        import_image: Any
        import_image_sequence: Any
        init_mesh: Any
        insert_sequence_blank: Any
        inside: Any
        is_pseudo_transparent_color: Any
        lasso: Any
        last_canvas: Any
        last_widget: Any
        layers: list[Layer]
        line_control: Any
        line_curve_stage: Any
        line_end: Any
        line_start: Any
        main_color: Any
        mask_all_enabled: Any
        mask_color_rgb: Any
        mask_color_rgbs: Any
        mesh_active: Any
        mesh_grid: Any
        mesh_original: Any
        mesh_points: Any
        middle_hand: Any
        move_sequence_image: Any
        move_timeline_cell: Any
        nearest_mesh: Any
        nearest_transform_handle: Any
        next_frame: Any
        next_key_frame: Any
        normalize_sequence_numbers: Any
        normalize_tone_curve_points: Any
        onion_all_layers: Any
        onion_center_percent: Any
        onion_next_color: Any
        onion_next_color_enabled: Any
        onion_next_count: Any
        onion_next_levels: Any
        onion_next_opacity: Any
        onion_next_rotation: Any
        onion_next_scale: Any
        onion_next_shift_x: Any
        onion_next_shift_y: Any
        onion_previous_color: Any
        onion_previous_color_enabled: Any
        onion_previous_count: Any
        onion_previous_levels: Any
        onion_previous_opacity: Any
        onion_previous_rotation: Any
        onion_previous_scale: Any
        onion_previous_shift_x: Any
        onion_previous_shift_y: Any
        onion_selected_colors_only: Any
        onion_shift_values: Any
        onion_skin: Any
        onion_transform_values: Any
        onion_tu_tb_scale: Any
        opaque_paint_color: Any
        opaque_rgb_color_count: Any
        paint_source_color: Any
        pan: Any
        paste_clipboard: Any
        pen_size: Any
        playback_advance: Any
        playback_frame_image: Any
        pressure_curve: Any
        pressure_curve_points: Any
        pressure_enabled: Any
        pressure_max: Any
        pressure_min: Any
        pressure_size_scale: Any
        pressure_value: Any
        previous_frame: Any
        previous_key_frame: Any
        push_doc_undo: Any
        push_layer_region_undo: Any
        push_layer_undo: Any
        push_undo: Any
        raster_triangle: Any
        rect_end: Any
        rect_start: Any
        redo: Any
        redo_stack: list[UndoEntry]
        history_branches: Any
        clear_history_branches: Any
        switch_history_branch: Any
        refresh_quality_preview_with_counter: Any
        report: Any
        request_quality_preview_counter: Any
        resolve_exposure_block: Any
        resolve_key_frame: Any
        rotate_selection_transform: Any
        rotation: Any
        sample: Any
        sample_color: Any
        select_exposure: Any
        selected_mask_colors: Any
        selected_used_color_rgbs: Any
        selected_used_colors: Any
        selection_bounds: Any
        set_zoom_around_canvas_center: Any
        set_zoom_around_widget_point: Any
        center_canvas: Any
        selection_clear_overlay: Any
        selection_mask_bool: Any
        selection_mask_override: Any
        selection_mask_rect: Any
        selection_outline_polygons: Any
        selection_polygon: Any
        sequence_entry_columns: Any
        set_brush_stabilizer: Any
        set_duration: Any
        set_layer_opacity: Any
        set_layer_visibility: Any
        set_onion_canvas_view_rotation: Any
        set_pen_size: Any
        set_playback_active: Any
        set_tool: Any
        set_transform_line_colors: Any
        set_transform_line_threshold: Any
        set_transform_mesh_grid: Any
        set_transform_quality: Any
        shape_end: Any
        shape_start: Any
        silhouette_layer_image: Any
        silhouette_non_background: Any
        stroke_before: Any
        sub_color: Any
        sync_numbered_image_from_cell: Any
        temp_tool: Any
        timeline_block_at: Any
        timeline_mode: Any
        timeline_step_columns: Any
        tone_curve_lut: Any
        tone_curve_samples: Any
        tool: Any
        transform_active: Any
        transform_apply_all_frames: Any
        transform_center: Any
        transform_drag_kind: Any
        transform_drag_points: Any
        transform_drag_start: Any
        transform_frame_index: Any
        transform_handle: Any
        transform_layer_index: Any
        transform_line_threshold: Any
        transform_mesh_cols: Any
        transform_mesh_grid: Any
        transform_mesh_reference_points: Any
        transform_mesh_rows: Any
        transform_mode: Any
        transform_original_has_content: Any
        transform_original_layer: Any
        transform_outer_polygon: Any
        transform_points: Any
        transform_preview_image: Any
        transform_quality: Any
        transform_quality_active: Any
        transform_rotation_handle: Any
        transform_source: Any
        transform_source_rect: Any
        transform_tp_line_colors: Any
        transform_tp_line_masks: Any
        transform_tp_masks: Any
        transform_tp_palette: Any
        transform_tp_prepared_preview: Any
        transformed_selection_outline: Any
        transparent_display_color: Any
        tween_pending: Any
        undo: Any
        undo_stack: list[UndoEntry]
        update_tool_cursor: Any
        update_transform_drag: Any
        visible_color_rgbs: Any
        warm_up_brush_runtime: Any
        widget_to_canvas: Any
        work_rect: Any
        zoom: Any
